name: Deploy via SSH

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod" 
          cache: true 

      - name: Install dependencies
        run: go mod tidy
  
      - name: Run tests
        run: go test ./...

      - name: Build Linux binary
        run:  main GOOS=linux GOARCH=amd64 go build -o uri2json main.go

      - name: Upload binary via SCP
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }} 
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          source: "uri2json" 
          target: "/home/${{ secrets.SSH_USERNAME }}/uri2json" 

      - name: Restart application via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mv /home/${{ secrets.SSH_USERNAME }}/uri2json /usr/local/bin/uri2json
            sudo chmod +x /usr/local/bin/uri2json
            sudo systemctl restart uri2json.service