on:
    push:
      branches: [ main ]
      tags: [ 'v*' ]
    pull_request:
      branches: [ main ]

jobs:
  lint-build-test:
    name: Lint, Build, Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build --all-features

      - name: Run Tests
        run: cargo test --all-features
        
      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  release:
    name: Create Release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: lint-build-test
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build Release
        run: cargo build --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated release for version ${{ github.ref_name }}
          files: |
            target/release/uri2json
            overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary via SCP
        uses: appleboy/scp-action@v0.1.6
        with:
            host: ${{ secrets.SSH_HOST }} 
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.PORT }}
            source: "target/release/uri2json"
            target: "/home/${{ secrets.SSH_USERNAME }}/uri2json" 
  
      - name: Restart application via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.PORT }}
            script: |
              echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > /home/${{ secrets.SSH_USERNAME }}/uri2json/.env
              sudo chmod +x /home/${{ secrets.SSH_USERNAME }}/uri2json/uri2json
              sudo systemctl restart uri2json.service